[net]
# more Docker friendly to use CLI git to fetch Cargo crates - see <https://github.com/rust-lang/cargo/issues/10583>
git-fetch-with-cli = true

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]

[target.aarch64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=mold"]
