name: docker

on:
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - config.toml

env:
  IMAGE: jameshiew/rustbuilder:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build --platform linux/${{ matrix.arch }} -t $IMAGE-${{ matrix.arch }} .
      - run: docker push $IMAGE-${{ matrix.arch }}

  push-multiarch-manifest:
    runs-on: ubuntu-22.04
    needs: build
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker manifest create $IMAGE --amend $IMAGE-amd64 --amend $IMAGE-arm64
      - run: docker manifest push --purge $IMAGE
